[package]
name = "infobip-api-rust-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
serde_json = "*"
tokio = { version = "*", features = ["full"] }
validator = { version = "*", features = ["derive"] }
lazy_static = "*"
regex = "*"

[features]
default = ["sms"]
sms = []